### ISSUE TITLE
Add support for Origin

### ISSUE THREAD

**Issue by MSIH** [dalion619/apple-mapkit-dotnet#1]
The Token to Use MapKit JS should contain origin 

origin — An optional claim that constrains the token to a specific website or domain. The value of this claim is a fully qualified domain, without a URL scheme (such as https://) that matches the origin header that the browser passes. For example, mywebsite.example.com. Optionally, you can use an asterisk (*) as the first character in the domain to match multiple subdomains. Don’t include a trailing slash as part of the origin claim.

https://developer.apple.com/documentation/mapkitjs/creating_and_using_tokens_with_mapkit_js

**Comment by dalion619** [comment]
Hi, the library is intended for backend use thus there is no origin.
