### ISSUE TITLE
Provide example project used for screen shots

### ISSUE THREAD

**Issue by MSIH** [dalion619/apple-mapkit-dotnet#2]
I am a newbie and trying to figure out how to use your project. could you include a demo project that you used to generate the screen shots?

**Comment by dalion619** [comment]
A demo project wouldn’t be possible as you’d need to use your Team & Key id.
After resolving the MapKit service you can create a snapshot url with,

mapkitClient.CreateSnapShotUrl(latitude, longitude, colorScheme);

You can try using Snapshot Studio, https://maps.developer.apple.com/snapshot
If it works there, it will work via the library.

**Comment by MSIH** [comment]
You can include the example site in the public repo and not include the values for setting up the service.

**Comment by dalion619** [comment]
Sorry I’m not sure what example site refers to, the snapshot url is https://snapshot.apple-mapkit.com/

CreateSnapShotUrl generates the signature for the image url which requires the configuration values for the service.
